### ISSUE TITLE
iojs support

### ISSUE THREAD

**Issue by ZloyDyadka** [wzrdtales/socket-io-sticky-session#1]
iojs supported?

**Comment by wzrdtales** [comment]
Currently not, there is an open pull request here https://github.com/indutny/sticky-session/pull/17#issuecomment-85278147

I have published this version, after month of no response from indutny. But now we're going forward to get this merged.

How fast du you need this, as I it would not be that much work to make it io.js/node 0.12 compatible and if you really need it I would do a last update of this package before everything gets merged into sticky sessions.

**Comment by ZloyDyadka** [comment]
I really need it :) Ty

**Comment by wzrdtales** [comment]
done

**Comment by wzrdtales** [comment]
ok wait I just realized that he does not patch the right function if I drop the check for the major version.

**Comment by wzrdtales** [comment]
ok now it's done ;)
