### ISSUE TITLE
socket.io  server lost connection

### ISSUE THREAD

**Issue by chuangtim** [wzrdtales/socket-io-sticky-session#13]
I have two  testing conputer as socket.io client ,there are 100 socket.io client  each conputer,it is ok when the first computer's 100 socket.io client connect  to  server ,but the second computer start to connect server，I found several client can't connect to server, why ? I had tried many times ,I found the same result, 

my nginx code 
```
    server {
	  listen 3000;
	  server_name socket.io.nodejs.com;
	  location / {
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection "upgrade";
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header Host $host;
	    proxy_http_version 1.1;
	    proxy_pass http://io_nodes;
	  }
	}

    upstream io_nodes {
	  #ip_hash;
	  server 127.0.0.1:3001;
	  #server 127.0.0.1:3002;
      keepalive 64;
	}
```

my server code 
```javascript
var cluster = require('cluster');
var fs = require('fs');
var net = require('net');

var argvIndex = 2;
var port = process.argv[argvIndex++] ? process.argv[argvIndex - 1]  : '3001';
var num_processes = require('os').cpus().length;

var sticky = require('socketio-sticky-session');

var options = {
  proxy: true, //activate layer 4 patching
  header: 'x-forwarded-for', //provide here your header containing the users ip
}

var server = sticky(options, function() {
  // This code will be executed only in slave workers

    var app = require('http').createServer();
    var io = require('socket.io')(app);
    io.on('connection', function (socket) {
        // console.log("a client connected";
        process.send({cmd:'notifyReq'});

        socket.on('cluster_test_message', function (data) {
            console.log('[socket.io msg] '+"worker"+cluster.worker.id+":"+'cluster_test_message = '+data);
        });

        socket.on('error', function (data) {
            console.log('[socket.io msg] '+'error = '+data);
        });

        socket.on('reconnect_error', function (data) {
            console.log('[socket.io msg] '+'reconnect_error = '+data);
        });

        socket.on('close', function (data) {
            console.log('[socket.io msg] '+'close '+data);
        });
    });

  return app;
}).listen(port, function() {
    
    console.log('Sticky cluster worker '
      + (cluster.worker ? cluster.worker.id : 'master')
      + ' server listening on port ' + port);
});
```

my client code
```javascript
self.socket = io.connect('http://'+'192.168.0.100:3000', {
      'forceNew': true,
      'reconnection': false,
  	});
```

**Comment by chuangtim** [comment]
console.log debug message at setupMaster function
```
   if (msg.cmd === 'sticky-session:ack') {
            patchConnection(msg, c, self);
          }else if(msg.cmd ==='notifyReq'){
            self.workers[i].connectedCounter++;
     }

  var log = setInterval(function () {
    console.log("worker 1:"+self.workers[0].connectedCounter+"   worker 2:"+self.workers[1].connectedCounter+"   worker 3:"+self.workers[2].connectedCounter+"   worker 4:"+self.workers[3].connectedCounter)
  }, 2000);
```
testing result

worker 1:0   worker 2:109   worker 3:0   worker 4:91
worker 1:0   worker 2:109   worker 3:0   worker 4:91
worker 1:0   worker 2:109   worker 3:0   worker 4:91
worker 1:0   worker 2:109   worker 3:0   worker 4:91

there are 91 connection only the client's shown;

**Comment by wzrdtales** [comment]
Unfortunately I have a hard time to reproduce your issue. Neither I know what exactly your problem is: Do you have any error codes or reproduceable cases nor I have essential inforation such as:

Used
- node version
- npm version
- socket-io-sticky-session version

Please supply all these details to be able to help you, thank you.

**Comment by chuangtim** [comment]
```
node.js version: v0.12.2
npm version v2.14
socket-io-sticky-session version: last version(0.41)
```
why npm version affect code?
I git clone your code yesterday,so it is last version.

**Comment by wzrdtales** [comment]
Simple question:

Why are you connecting directly to self.socket 192.168.0.100:3000, but still activate layer 4 patching through `proxy`set to `true`?

**Comment by chuangtim** [comment]
I am testing socket.io sticky session ,server and nginx are one computer which ip is 192.168.0.100 ,nginx proxy 3000 port and pass connection to socket.io server which listening 3001 port.

**Comment by wzrdtales** [comment]
ok have overseen this, please log socket.on('error' events on client and server side and also get logs from nginx error log and lets continue with those, or try to prepare an executable test that is able to reproduce your scenario as I have tested it yesterday and everything worked fine for me that day.

**Comment by chuangtim** [comment]
do you test your code with different ip?can u show me configure?

**Comment by wzrdtales** [comment]
Do not have it at hand right now, but can show you later. But yes default transport, connecting with domain instead of ip and I tested it on local network with different ips as also on one of my webservers from multiple other ips.

**Comment by chuangtim** [comment]
OK,thanks for your answer,I will test it again tonight.
