### ISSUE TITLE
sticky(server).listen not working

### ISSUE THREAD

**Issue by naholyr** [wzrdtales/socket-io-sticky-session#3]
Sample code:

```js
var sticky = require("socketio-sticky-session")
var http = require("http")

sticky(http.createServer(function (req, res) {
  res.end("hello")
})).listen(8081)
```

Result is infinite display of this error:

```
/…/project/node_modules/socketio-sticky-session/lib/sticky-session.js:204
    throw new Error('Worker hasn\'t created server!');
          ^
Error: Worker hasn't created server!
    at StickyAgent.setupSlave (/…/project/node_modules/socketio-sticky-session/lib/sticky-session.js:204:11)
    at sticky (/…/project/node_modules/socketio-sticky-session/lib/sticky-session.js:100:18)
    at Object.<anonymous> (/…/project/sticky-sample.js:6:1)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:117:18)
    at node.js:948:3
```

**Comment by naholyr** [comment]
Note that the function form seems to be working, maybe you can just remove this usage from README

**Comment by wzrdtales** [comment]
This example has worked, I will take a look into it why I does not anymore.
Thank you for reporting

**Comment by afrantz** [comment]
Same issue for me

**Comment by wzrdtales** [comment]
Ic, this is because of `http.createServer` obviously returning an object and not a function.

**Comment by afrantz** [comment]
Thank you !
Can you publish your package on NPM please ?

**Comment by wzrdtales** [comment]
yeh, i'm going to publish it in some minutes. Just got an urgent case in here and was away for a while.

**Comment by wzrdtales** [comment]
published as 0.3.0

**Comment by afrantz** [comment]
Thank you a lot ! ;)

**Comment by SeanChristopherConway** [comment]
Kind of late to this thread but I had the same issue. I solved it by following the answer here: http://blog.doselect.com/post/137732962198/nodejs-clustering-maintaining-sticky-session

Which is, if the site is down or whatever, that you need to return the server in the sticky function for it to be accessible in the .listen function, thus you should do:

```
var sticky = require("socketio-sticky-session")
var http = require("http")

sticky(return http.createServer(function (req, res) {
  res.end("hello")
})).listen(8081)
```
