### ISSUE TITLE
news about support for 0.12?

### ISSUE THREAD

**Issue by liorsion** [wzrdtales/socket-io-sticky-session#4]
as it got stable.. ? Any additional info on what stopped working, maybe I can help?

**Comment by wzrdtales** [comment]
I actually made already a verison of 0.12, we were working on get this merged into the origin. But we stopped at some point, I will look into merging it into this version also and continue working and getting it merged completely.

**Comment by wzrdtales** [comment]
I merged the version with 0.12 support and released under 0.3.0.
