### ISSUE TITLE
Case insensitive header

### ISSUE THREAD

**Issue by shukydvir** [wzrdtales/socket-io-sticky-session#5]
Hi,

I wise to know why the header is case insensitive?

Can we make it case sensitive?

Thanks

**Comment by wzrdtales** [comment]
Because of http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

Or do you want the content of the http header to be case sensitive? Everything after the colon, please describe your use case, to give me a chance to understand the problem you're trying to solve.

Thank you

**Comment by shukydvir** [comment]
Thanks,

My use case is as follows, i'm using Elastic Beanstalk with ELB to route socket.io traffic to my application server running socket.io.

In ELB I enabled proxy protocol support that moves the users ip to the application server via the header.
The header it is transferring via Nginx is 

 X-Forwarded-For

which I believe is case sensitive, do you have any experiance with it? I still need to do extensive testing to see if it works but it will only happen in the begging of next week and I'd be happy to update.

Also I didn't see in your code any code downcasing or upcasing the header? are you doing it some where?

Thanks

**Comment by wzrdtales** [comment]
Yes here: https://github.com/wzrdtales/socket-io-sticky-session/blob/master/lib/sticky-session.js#L239

No it is not, take a look at the rfc also posted in my last comment:
http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

Fields are case-insensitive defined by the HTTP standard.

**Comment by shukydvir** [comment]
I'm currently in the w3 page you send and i'm looking at the headers there:

<img width="380" alt="screen shot 2015-11-12 at 8 34 04 pm" src="https://cloud.githubusercontent.com/assets/711187/11127416/e6073766-897c-11e5-9047-c4321e3b371e.png">

And as you can see there is consensus that all headers start with a capital letter.

The fact that it's supposed to be case insensitive means that you should ignore casing but what you are doing is making it case sensitive to lower case.

I believe it should be changed and should not explicitly lower case the header.

**Comment by liorsion** [comment]
I think a better solution is to lower case the header when it's set, I'll send a pull request in a short whilte

**Comment by wzrdtales** [comment]
@liorsion Yes that makes sense.

**Comment by wzrdtales** [comment]
Thank you for your contribution on this, lower casing here is one way to have a case-insensitive handling, but it really doesn't matter if it does start with a capital letter or not.

This has been published as patch under version v0.3.1.
