### ISSUE TITLE
Worker ID

### ISSUE THREAD

**Issue by chrizz1001** [wzrdtales/socket-io-sticky-session#6]
How to get the worker id inside the `sticky(options, function() {});` ? I have grunt tasks running at startup that should only run once, not for each instance. So I have to change the config for the workers accordingly.

**Comment by wzrdtales** [comment]
Currently not really possible:
https://github.com/wzrdtales/socket-io-sticky-session/blob/master/lib/sticky-session.js#L200

We do not pass anything through the callback, we could add it though. Yet you could only use the pid via `this.process.pid` right now. But I also would not mind to add this as a parameter to the callback.

**Comment by chrizz1001** [comment]
Ok, then I think I have to go another way. Thx for the info!
