### ISSUE TITLE
UncaughtException: Socket error

### ISSUE THREAD

**Issue by llambda** [wzrdtales/socket-io-sticky-session#9]
When I put into production behind a reverse proxy on linode.com I get the following error every time the reverse proxy checks server health:

```
uncaughtException: Error: read ECONNRESET
    at exports._errnoException (util.js:855:11)
    at TCP.onread (net.js:544:26)
```

I was able to identify the problem socket at https://github.com/wzrdtales/socket-io-sticky-session/blob/master/lib/sticky-session.js#L280

If I add:

socket.on('error', function (err) { console.log('err ' + err)});

it is logged, confirming the source of the issue.

**Comment by wzrdtales** [comment]
It always help if you add a test scenario e.g. a script that actually raises the problem. I will try to reproduce this however.

**Comment by llambda** [comment]
Yeah, a test would be great. I am not sure how to write it since I think the test would need to open a TCP connection to the server, and end the connection immediately, which I am not sure is possible without kernel level code. The uncaught exception crashes the processes, because of unhandled 'error' event (this is just the standard node behavior).

**Comment by wzrdtales** [comment]
a raw tcp connection is not that complicate, not so much of kernel level code :)

As you said the problem is at the synced republish, when do you call the sync event in your implementation?

**Comment by llambda** [comment]
I think #12 will fix this.

**Comment by wzrdtales** [comment]
Awesome, going to check this out soon. Thank you

**Comment by wzrdtales** [comment]
Fixed and published as + socketio-sticky-session@0.4.0

See the mentioning commit for details.

Reopen if this is still not fixed for you.
Thanks for reporting!

**Comment by llambda** [comment]
Many many thanks @wzrdtales !

**Comment by wzrdtales** [comment]
No problem @llambda 

Also to note I have just also released another patch + socketio-sticky-session@0.4.1 which supports pauseOnConnect if you use a node version greater than 0.12 and automatically uses it. This also fixes randomly connections being "frozen" because data was lost.
